### ISSUE TITLE
Login at backend, respond with status 401

### ISSUE THREAD

**Issue by Offerel** [Offerel/SyncMarks-Extension#44]
Sorry to say it's the same with login only after I have logged in in another tab at your site. I passed the SSL_ERROR_BAD_CERT_DOMAIN, and tested the other domain too.
I also tested with my webapp from Linux-Buster with the same result.
There must be something in the addon not working for me in three different computers.
The addon doesn't work in Edge and Chrome for me. In the older 1.17.3 I could put in the  credentials, but not having the addon to login.
Thank you for tonight!

_Originally posted by @johmor52 in https://github.com/Offerel/SyncMarks-Webapp/issues/62#issuecomment-798781781_

**Comment by johmor52** [comment]
Still the same, can't save without having a logged in tab open.
Save without tab logged in:
SyncMarks Error:Error set name of client.401

Installation i Chrome and Edge (not firefox) Got Error:
"browser_specific_settings": {
		"gecko": {
			"strict_min_version": "86.0",
			"id": "syncmarks@offerel.com"
		}
	},

In local net I don't have to have a tab open
I can transfer bookmarks from Firefox.

**Comment by Offerel** [comment]
You can ignore that error. Chromium does this to. Its only there for Firefox. strict_min because Firefox has changed permissions or at least fixed them with version 86. The addon will have issues with Firefox < v86.x. The id is to save profile changes for a temporary between installations. Both are not present in the release version. 

`SyncMarks Error:Error set name of client.401.` As said before, the request you send, seems not to be complete. Something is missing in your credentials, either username or password or both.

**Comment by johmor52** [comment]
If I open a instance of Firefox and log into webapp and then open a new instance of Firefox I can save extension. If I close the first instance, I still can save. If I close both instances and open a new Firefox, I can't save and got 401 error, as the logged in session is closed.
If I have webapp at my webhotell there must be something stopping extension to log in.
I have absolutely the same installation i a linux machine with Debian Buster and php7.3. In that machine the webapp let the extension save without a login before in a tab or window.
Here are my backup and log (changed password durint test, could not make another user...):
[SyncMarks.log](https://github.com/Offerel/SyncMarks-Extension/files/6175522/SyncMarks.log)
[SyncMarks_Options_2021-03-20.txt](https://github.com/Offerel/SyncMarks-Extension/files/6175524/SyncMarks_Options_2021-03-20.txt)
(changed to .txt because of rules)

**Comment by Offerel** [comment]
Ahhhh, ok. I think i have an idea, give me some minutes.

**Comment by Offerel** [comment]
Unfortunately, i have made yesterday some changes with Import/Export functionality for the WebApp and i must keep this in sync with the Extension. As of now, I have uploaded a new commit for the WebApp [b9f557c](https://github.com/Offerel/SyncMarks-Webapp/commit/b9f557c6a49e018b12ceb3bad8b65181a285c164) in the dev branch. Maybe i have now found the issue for not saving your data in the Extension. For this i have made also a new commit [beba8c7](https://github.com/Offerel/SyncMarks-Extension/commit/beba8c711608f83c96e5bfced3309ea998fc417f).

Testing only the saving functionality, will work also with the WebApp 1.4.1, however for import/export bookmarks, you need WebApp 1.4.2, which is only available as a first draft in dev branch.

I can make a pre-release, if you want, if saving is now working for you or if this makes the things easier for you. Please let me know.
